etcd:
  image: gcr.io/google_containers/etcd:2.2.1
  net: host
  command: ['/usr/local/bin/etcd', '--addr=127.0.0.1:4001', '--bind-addr=0.0.0.0:4001', '--data-dir=/var/etcd/data']

master:
  image: gcr.io/google_containers/hyperkube:v1.1.8
  net: host
  pid: host
  privileged: true
  volumes:
    - /sys:/sys:ro
    - /dev:/dev
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/lib/kubelet/:/var/lib/kubelet:rw
    - /var/run:/var/run:rw
  command: ['nsenter', '--target=1', '--mount', '--wd=.', '--', './hyperkube', 'kubelet', '--hostname-override=127.0.0.1', '--address=0.0.0.0', '--api-servers=http://localhost:8080', '--config=etc/kubernetes/manifests', '--cluster-dns=10.0.0.10', '--cluster-domain=cluster.local']

proxy:
  image: gcr.io/google_containers/hyperkube:v1.1.8
  net: host
  pid: host
  privileged: true
  command: ['/hyperkube', 'proxy', '--master=http://127.0.0.1:8080', '--v=2']

kube2sky:
  image: gcr.io/google_containers/kube2sky:1.12
  net: host
  command: ['--kube_master_url=http://127.0.0.1:8080', '--domain=cluster.local']

skydns:
  image: gcr.io/google_containers/skydns:2015-10-13-8c72f8c
  net: host
  command: ['--machines=http://localhost:4001', '--addr=0.0.0.0:53', '--domain=cluster.local', '-ns-rotate=false']
